name: typsense-github-action-demo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      typesense:
        image: typesense/typesense:0.22.0
        env:
          TYPESENSE_API_KEY: dskrpt
          TYPESENSE_DATA_DIR: /data
          TYPESENSE_ENABLE_CORS: true
        ports:
          - 8108:8108
        options: >-
          --health-cmd "curl http://127.0.0.1:8108/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        volumes:
          - ts_data:/data

    steps:
      - uses: actions/checkout@v2

      - name: curl Typesense
        run: curl http://localhost:8108/health
